###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mariadb:
        container_name: rrhh-db
        image: 'mariadb:10.10'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=admin
            - MYSQL_DATABASE=admin
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
        ports:
            - '5050:3306'

    webserver:
        image: 'nginx:alpine'
        container_name: rrhh-webserver
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8082:80'

    php-fpm:
        build: phpdocker/php-fpm
        container_name: rrhh-php
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
